### ISSUE TITLE
Create demo link

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.draw.js#1]
Hi,

I believe you should add a bit more documentation for this project: maybe a demo link showing what it can do?

**Comment by Fuzzyma** [comment]
Jeah maybe I should add demos. I never came this far till now...

**Comment by Fuzzyma** [comment]
I reworked the whole thing. I hope the doc is better now.
I also added a github-page and a demo-page (http://fuzzyma.github.io/svg.draw.js/demo/index.html)
