### ISSUE TITLE
Circles visible when drawing a line

### ISSUE THREAD

**Issue by albohlabs** [svgdotjs/svg.draw.js#10]
When I draw a polyline the little circles are created on the wrong position. 

![output](https://cloud.githubusercontent.com/assets/163665/17219276/1383d28c-54eb-11e6-9734-c8ba9aba8931.gif)

Testet in current FF version.

**Comment by Fuzzyma** [comment]
Can I see your code? Also: Do you use any transformation?

**Comment by albohlabs** [comment]
> Do you use any transformation?

No i dont't.

I've debugged a little bit, cause my code is really simple and straight forward.

A problem in chrome is that `this.parent.node.getBoundingClientRect().x` is `undefined` and the [calculation of `offset.x` results in `NaN`](https://github.com/Fuzzyma/svg.draw.js/blob/master/dist/svg.draw.js#L362).

![bildschirmfoto 2016-07-29 um 10 02 13](https://cloud.githubusercontent.com/assets/163665/17241710/8f1a0b0e-5573-11e6-8b1d-7ec777146a08.png)

This results in `cx` and `cy` to be zero.

![bildschirmfoto 2016-07-29 um 10 03 43](https://cloud.githubusercontent.com/assets/163665/17241760/d89ca3b8-5573-11e6-800b-1535bbe09bea.png)

I don't know why the [x- and y-coord transformation](https://github.com/Fuzzyma/svg.draw.js/blob/master/dist/svg.draw.js#L370) is needed, but when I removed it the dots were placed correctly in FF. 😅

![output](https://cloud.githubusercontent.com/assets/163665/17242056/72d8019c-5575-11e6-86d3-fdbd9035a18f.gif)

**Comment by Fuzzyma** [comment]
Cool and where is your code? :P

**Comment by albohlabs** [comment]
Here it is :)

``` javascript
drawTool({type}) {
    let annotation;
    this.draw
        .on('mousedown.draw', e => {
            e.stopPropagation();

            annotation = this.createDrawElement(e);
        })
        .on('mouseup.draw', e => annotation.draw('stop', e));
}

createDrawElement(e) {
    const svgNode = this.draw.polyline()
        .attr({
            fill: 'none',
            color: this.color,
            'stroke-width': this.strokeWidthSelection
        });

    svgNode
        .on('drawstop', () => this.onDrawStop(type, svgNode))
        .draw(e);

    return svgNode;
}
```

I think the magic of `onDrawStop` is less important.

Also remarkable is that the `viewBox` property of the svg element is set to `0 0 2940 3600`. 

Hm, did i miss something? 🤔

**Comment by Fuzzyma** [comment]
haha - ok I cant just copy and paste that :D. Its hard to reproduce it that way. Would you mind breaking down your code to a miminum so I can just take it and put it into a fiddle to try it out?

**Comment by albohlabs** [comment]
Ups, sorry. Yeah of course I will do that in a free minute.

**Comment by Fuzzyma** [comment]
@albohlabs any news on your code? :)
