### ISSUE TITLE
Drawing poly shapes without little circles

### ISSUE THREAD

**Issue by GuskiS** [svgdotjs/svg.draw.js#11]
Is it possible to remove little circles that are being created while drawing poly shapes?
At the moment, I have this solution:

``` js
polyline = draw.polyline().draw(e);
polyline .remember("_paintHandler").drawCircles = function() {};
```

It is ugly and hackish way. Maybe a way with options?

**Comment by Fuzzyma** [comment]
You can create a PR with this feature. At the moment there is no other way.

**Comment by p0rsche** [comment]
Just use your own plugin that overwrites the default behavior. Here is mine: https://jsfiddle.net/p0rsche/w80x3rcm/
Actually it's copied from svg.draw.js sources with removed drawCircles() method.

**Comment by giiska** [comment]
I think the best way is to expose options to `draw` method, like:
```
draw({snapToGrid:15, circleSize: 5})
```
