### ISSUE TITLE
SnapToGrid with transform (x or y) causes negative starting points

### ISSUE THREAD

**Issue by gurraw** [svgdotjs/svg.draw.js#15]
Trying to center line endings in the grid cells using the code below. Works everywhere except at the very  top and at the far left. where the starting point is set to -64 (x resp y) instead of 0.

```js
var drawing = SVG('svgDrawLayer');
var rect = drawing.polyline().attr('stroke-width',1).transform({x:32, y:32});
drawing.on('mousedown', function(e){		
            rect.draw(e, {snapToGrid:64});
        }, false);
drawing.on('mouseup', function(e){
            rect.draw('stop', e);
        }, false);
```

**Comment by Fuzzyma** [comment]
@gurraw if this is still an issue after all those years, let me know. I will close for now.
