### ISSUE TITLE
.draw() usage is ambiguous 

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.draw.js#16]
`.draw()` usage is ambiguous. Take the following code snippet:

```js
const drawing = SVG('mua_logo')

drawing.on('dblclick', event => {
	/* not working - click events are not handled */
	//const line = drawing.polyline().draw(event)

	const line = drawing.polyline().draw()
	line.draw(event)
})
```
_live example: https://github.com/dotnetCarpenter/mua_

I'm not sure why, but if I do `drawing.polyline().draw(event)` as oppose to `drawing.polyline().draw().draw(event)`, the click event is no longer handled by svg.draw.js.

**Comment by Fuzzyma** [comment]
The event you pass to the draw function is used to start the drawing process as well as setting points in case of poly shapes. In your case you bound `drawing.polyline()` to the `dblclick` which means with every double click you create a _new_ shape and start the drawing process with it.
Correctly your code should looks something like this:

```js
const drawing = SVG('mua_logo')
const line = drawing.polyline()

drawing.on('dblclick', event => {
	line.draw(event)
})
```

[And thats working](https://jsfiddle.net/8spu85xs/)

**Comment by dotnetCarpenter** [comment]
Not really. I want to begin a new polyline with each double click and let svg.draw.js handle the single click case.

**Comment by dotnetCarpenter** [comment]
You can try it here: https://dotnetcarpenter.github.io/mua/simpel.html
Use `z` to finish a polyline

**Comment by Fuzzyma** [comment]
Well jeah. I see now what happens. Normally when you start drawing with `el.draw(event)` the event is used as point setter also. In your case that would be doublclick but you want click. So you start the normal draw process with `drawing.polyline().draw()` which binds the start/point do click by default and you set the first point with `line.draw(event)`. However it is less ambiguous when you write `line.draw('point', event)` instead which describes better what you want.

So that would be:
```js
const drawing = SVG('mua_logo')

drawing.on('dblclick', event => {
	const line = drawing.polyline().draw()
	line.draw('point', event)
})
```

**Comment by dotnetCarpenter** [comment]
`line.draw('point', event)` looks good to me but unfortunately that doesn't work. It won't add the first point since the `event` variable is not an instance of `Event`.

```js
// When we got an event we have to start/continue drawing
if (event instanceof Event) {
    paintHandler['start'](event);
}
```
_from [line 193 in svg.draw.js](../blob/0551e2ce05a6106d733ddc3b15ade257ef165f56/src/svg.draw.js#L193)_ 

Mimicking this line can be achieve with `line.draw('start', event)` but I'm not sure this your intended API?

**Comment by Fuzzyma** [comment]
Ah yes sure - the drawing process starts with the first click when the default is used. Since it wasn't clicked until then  we have to start the draw first ourselves. As mentioned in the docs all methods are available but not often needed for standard cases. So you might use it this way indeed. Maybe I should map point() to start() when no draw process was started until then...

**Comment by dotnetCarpenter** [comment]
> Maybe I should map point() to start() when no draw process was started until then...

Not sure if this will not only complicate things, when better documentation might help. Dynamic functions can get can really hairy to maintain because the code path for similar calls changes. But it's your plugin and your call.

I looked in the README.md and there is no mention of `'start'`. I wanted to add that and submit a PR but I'm getting confused about the wording.

>`svg.draw.js` populates its methods it uses to draw the shape. This is useful in edge-cases but generally not needed. However the method `done` is needed for poly-shapes and `cancel` can be called on every shape to stop drawing and remove the shape.
>
>```js
>	// Finishes the poly-shape
>	polygon.draw('done')
>
>	// Cancels drawing of a shape, removes it
>	polygon.draw('cancel')
>
>	/* The following are only useful in edge-cases */
>
>	// Set the first point of a drawing in case you're initiating svg.draw.js in
>	// an event listener as oppose to the default click handler setup by svg.draw.js.
>	polygon.draw('start', event)
>
>	// Draws a new point with the help of (mouse-)event
>	polygon.draw('point', event)
>
>	// Draws the point while moving the mouse (basically the animation)
>	polygon.draw('update', event)
>
>	// Stop drawing, cleans up
>	polygon.draw('stop', event)
>```

Is this correct? **Set the first point of a drawing in case you're initiating svg.draw.js in an event listener as oppose to the default click handler setup by svg.draw.js.**

**Comment by Fuzzyma** [comment]
Albeit I agree with you about better documentation I think in this special case it's very confusing to have 2 different methods to set a point. `start()` sets a point as well as `point()` does. Only that `point()` does not set the first point. That's stupid. If the user wants a point he gets a point - that's how it should be. That would also allow to only document one of these methods since they basically map to the same functionality. 
Guess I have to think about that again...

**Comment by dotnetCarpenter** [comment]
I'm warming up to your idea about swapping functions, so `.point()` points to `.start()` in the first call.

**Comment by Fuzzyma** [comment]
please take a look into the current master where I kinda hacked that in. I will review the whole plugin for svg.js v2.5 and change a lot. But for now I dot want to force an api change. Please check if your usecase is fixed so I can release this under 2.0.3

**Comment by dotnetCarpenter** [comment]
I see the change in [src/svg.draw.js](https://github.com/svgdotjs/svg.draw.js/blob/4360e0ea61cde364eec1cbebc92f05a7404c1047/src/svg.draw.js#L90) but it has no effect.

Ahh wait. I thought the change meant that I could do:
```js
drawing.on('dblclick', event => {
	/* not working - click events are not handled */
	const line = drawing.polyline().draw(event)

	lines.push(line)
})
```

But the only change is that instead of doing:
```js
drawing.on('dblclick', event => {
	/* not working - click events are not handled */
	//const line = drawing.polyline().draw(event)

	const line = drawing.polyline().draw()
	line.draw('start', event)

	lines.push(line)
})
```

I can now do:
```js
drawing.on('dblclick', event => {
	/* not working - click events are not handled */
	//const line = drawing.polyline().draw(event)

	const line = drawing.polyline().draw()
	line.draw('point', event)

	lines.push(line)
})
```

Not sure if that is much of an improvement. The documetation says:

>You can use your own mouse-events. Just pass the event-Object to the draw-Function
>```js
>var drawing = SVG('myDrawing');
>var rect = draw.rect();
>
>draw.on('mousedown', function(event){
>    rect.draw(event, options);
>});
>draw.on('mouseup', function(event){
>    rect.draw(event);
>}>);
>```

I rather like that to be true.

**Comment by dotnetCarpenter** [comment]
Here is a working demo with the current publish version of svg.draw.js (and with my work-arounds): https://dotnetcarpenter.github.io/mua/

This issue can be seen in the top of `js/app.js`.

**Comment by dotnetCarpenter** [comment]
The changes I made in this issue and #17 is in the `newDraw` branch if you want to play around with it.

**Comment by Fuzzyma** [comment]
Ok I try to explain the whole thing again:
When you call `draw()` with no parameter, it binds to the `click` event by default. However that means that it starts the drawing process when you click somewhere and not before. So when you want to set a point you need to do that manually by calling `draw('point', event)` or `draw.event()`.

When you do not want to bind click by default you need to pass an event argument which is instead used to start teh drawing process. However that means, that you need to manage the whole drawing process yourself. The plugin wont take over again.

So in your case: You want to start the drawing process on dblclick but after that you want to use click so you have 2 possibilities

- the one discussed above with setting the first point manually but letting `draw()` bind to click by default
- you manage everything alone - and that would kinda look like this:

```js
var dblclickHandler = function(ev) {
  // dont start another drawing when oldone isnt finished yet
  canvas.off('dblclick', dblclickHandler)

  // start drawing process. dont bind to default click. draw first point
  var line = canvas.polyline().draw(ev).stroke('black')
  
  // bind to click and draw a point on every click
  var clickHandler = function clickHandler(ev) {
    line.draw('point', ev) // or line.draw(ev)
  }
  canvas.on('click', clickHandler)
  
  // wait for enter keydown and finish shape. unbind/bind events
  SVG.on(document, 'keydown', function keydownHandler(ev){
    // finished by enter
    if(ev.keyCode == '13') {
      line.draw('done')
      SVG.off(document, 'keydown', keydownHandler)
      canvas.off('click', clickHandler)
      canvas.on('dblclick', dblclickHandler)
    }
  })
}

canvas.on('dblclick', dblclickHandler)
```

Thats tested - it works. However - if you want to use click for points is easier to use the magic default bind.
Hope its clear now how this all works. You have to manage the drawing process yourself entirely when you want control. The defaul click handler is just a bonus and for new people to have a result immidiately

**Comment by dotnetCarpenter** [comment]
I think this is a prime example! and something that should be in the readme. I might make a PR, if I find time and the right words. Thanks a lot!
