### ISSUE TITLE
Is there any support of story?

### ISSUE THREAD

**Issue by YakovL** [svgdotjs/svg.draw.js#20]
So I'd like to build an editor which supports undo/redo – at least for the current session but ideally with stored story. Is there any means to do that in svg.draw.js or I have to implement this? Any suggestions on how to do this appropriately?

**Comment by Fuzzyma** [comment]
Sorry for the late reply. At the moment there is nothing like this. I also think that's its tricky to implement. Of course you can save whole shapes and undo/redo them but not the drawing process itself. There is no way to "attach" to a drawing session. You surely can hack it in but it's not designed yet
