### ISSUE TITLE
Browsers support

### ISSUE THREAD

**Issue by inanisvitae** [svgdotjs/svg.draw.js#21]
It looks like svg.draw.js has really poor cross browser support. It behaves completely differently when running on different modern browser.

**Comment by Fuzzyma** [comment]
Please create a fiddle showing your issues. Show examples of what's wrong.

**Comment by inanisvitae** [comment]
How exactly do you use cancel on a polygon?
Is it like

polygon.draw('cancel') or polygon.fire('cancel') ?

**Comment by Fuzzyma** [comment]
How is this in any way related to the issue? 

It's draw('cancel") as stated in the docs

**Comment by inanisvitae** [comment]
I have exactly the same code on chrome and firefox, but chrome doesn't cancel drawing polygon while firebox does

**Comment by Fuzzyma** [comment]
Please create a fiddle which shows this issue!

**Comment by inanisvitae** [comment]
Do you know what does TypeError: this.set is undefined mean?

**Comment by Fuzzyma** [comment]
Man please just create that fiddle! There is no worth in this question when I can't reproduce it. 
So take your code, chunk it down to the minimum and put it on jsfiddle. This way I can see what you did and how and catch the problem
