### ISSUE TITLE
Window offset alternative

### ISSUE THREAD

**Issue by jc5826** [svgdotjs/svg.draw.js#27]
I noticed that the plugin makes adjustments based on the scroll position of the 'window' but in my application I have a scrolling div.  So, I made some changes so I can pass in the target window. e.g.

  rect.draw(e, {scrollTarget: $("#drawing")});

Pardon the jQuery code snippet but it was convenient for my purposes.

Here's what worked for me based on v2.0.3 - 2017-06-19

[patch.txt](https://github.com/svgdotjs/svg.draw.js/files/1423061/patch.txt)

**Comment by Fuzzyma** [comment]
@jc5826 sorry for never replaying. That would have actually be a nice edition. If you ever have the muse to do so, feel free to create a PR to integrate that behavior. For now I will close this :)
