### ISSUE TITLE
Use in Angular5

### ISSUE THREAD

**Issue by aplongh** [svgdotjs/svg.draw.js#29]
First of all, GREAT library, thanks for sharing. I am trying to use it in an Angular5 Project, but have been unable to set it up (when trying "drawing.rect().draw()", it says ...draw is not a function.

Has anyone been able to use it in an Angular5 scenario?

Thx

**Comment by Fuzzyma** [comment]
Did you include the `svg.draw.js` plugin? Without it `.draw()` is simply not defined

**Comment by Matimen** [comment]
Hello,

How can i import svg.draw.js in Angular 2+?

Thank you for your help

**Comment by Fuzzyma** [comment]
I guess you are better off asking that on stackoverflow. I don't use angular or typescript so I simply have no idea
