### ISSUE TITLE
calc function missing

### ISSUE THREAD

**Issue by jrknob** [svgdotjs/svg.draw.js#3]
Hi. I really like your work with these svg.js plugins! It seems that the version of svg.draw.js here is missing a calc prototype function. I can use the minified version from your demo page and it works fine. 

Thanks.

**Comment by Fuzzyma** [comment]
Hey, are you using the version from the dist directory? The calc function is a dynamic function which is generated on runtime. 
What is the error you are getting?

**Comment by jrknob** [comment]
Sorry for the delay. I updated again from the dist package and am no longer seeing the calc error. I apologize if I used the wrong process here. I am new to GitHub.

**Comment by jrknob** [comment]
I'm still not able to run the demo properly though. Getting 'rect.draw' is not a function. I have loaded svg.js and svg.draw.js from your zip in the demo page. 

I have: div with id "drawing" in my markup and on page load I run this:

var drawing = new SVG('drawing').size('100%', '100%')
drawing.rect.draw();

I see the first JS line creates the SVG element within my div but the second line gives the error.

**Comment by jrknob** [comment]
Never mind. I got working. Thanks.
