### ISSUE TITLE
How to draw curves?

### ISSUE THREAD

**Issue by amitguptagwl** [svgdotjs/svg.draw.js#30]
Thanks for writing such useful library. I'm looking for some library for my image labeling tool [imglab](https://github.com/NaturalIntelligence/imglab). So I've some questions;

* Can this library help me to draw quadratic and bezier curves?
* Can I draw with given points?
* Can I manipulate shapes once the are drawn?

**Comment by Fuzzyma** [comment]
1. No this library cannot draw paths. This needs yet to be added
2. I am not sure what you mean. You can place points of a polygon by hand but beside that...
3. You need svg.resize.js for this job

**Comment by amitguptagwl** [comment]
Thanks for your response.
