### ISSUE TITLE
Draw multiple Rectangle

### ISSUE THREAD

**Issue by M-Husein** [svgdotjs/svg.draw.js#32]
Hi, Thanks for your library,
Nice work.

I have problem, to draw multiple rectangle, I following your demo with event draw mouseup, draw mousedown and rect drawstop but I can't create multiple rectangle cause your demo removeListener for all next event.

Please give me some guide to implement this.

**Comment by Fuzzyma** [comment]
Those questions are better asked on stackoverflow and not in the issue tracker. We have a dedicated tag at stackoverflow where far more people are willing to help which will resolve your issue even faster.

**Comment by audas** [comment]
This answer is a shame as nothing at all is being addressed on stackoverflow in regards to this extension of svg.js and it would seem addressing the **ISSUE** here would be most helpful.

While svg.js seems to be responded to - this is not.

**Comment by Fuzzyma** [comment]
@audas I follow the tag svg.js on stackoverflow. I get mails when questions are asked with this tag. I dont get a mail immediately so it can take its time until I answer. If your question does not land in my inbox, I am sorry but I cant do much about it.

**Comment by Fuzzyma** [comment]
https://stackoverflow.com/questions/55530152/draw-multiple-rectangles-with-svg-draw-js#55530434
