### ISSUE TITLE
What is the right way to add attributes

### ISSUE THREAD

**Issue by pavlovt** [svgdotjs/svg.draw.js#33]
Hi,
I would like to add to the drawing polygon fill="none" - what is the right way to do it?
Here is my code: 
```javascript
var poly = new SVG('rooms').size('100%', '100%')
            .polygon().draw({snapToGrid:10})var poly = new SVG('rooms').size('100%', '100%')
            .polygon().draw({snapToGrid:10})
```
I could add it like that: 
```javascript
poly.on('drawstart', function() {
      $(poly.node).attr({strokeWidth: 1, fill: 'none', stroke: '#000000'})
});
```
but it looks ugly - is there a better way?

**Comment by Fuzzyma** [comment]
Please ask questions on stackoverflow. There are lots of people who will help you with this simple question.
Or you just go to the docs and search for `fill`: http://svgjs.com/manipulating/#fill

```js
el.fill('none')
```
