### ISSUE TITLE
Create a plein polygon

### ISSUE THREAD

**Issue by hatim05** [svgdotjs/svg.draw.js#34]
How I can create a plein document, actually we can drow any kind of polygon

**Comment by Fuzzyma** [comment]
http://svgjs.com/elements/#svg-polygon
http://stackoverflow.com

**Comment by hatim05** [comment]
Hello, 

Actually  we can create polygons like this attached, but we want plein polygons 
![bp](https://user-images.githubusercontent.com/40993954/42444751-2489fcbc-8371-11e8-9254-185d99341b1f.png)

**Comment by Fuzzyma** [comment]
What is a plein polygon? There is no word like `plein`. Do you mean `plain`? If yes, what do you mean by plain polygon? I dont get it. And again: thats a question for stackoverflow!
