### ISSUE TITLE
Continue drawing existing object

### ISSUE THREAD

**Issue by teetkalm** [svgdotjs/svg.draw.js#39]
Hello,
I'm struggling to find a way, how to edit existing object (like resizing/moving rectangle, circle etc), but found no coding examples. I tried someting like that, but it does not work:
```
//passing SVG node to function:
function editShape(el){
   SVG.get(el.id).draw(); //nothing happens
}
```
Please help.

**Comment by Fuzzyma** [comment]
Dont open an issue when you already posted on stackoverflow. I even commented there.

**Comment by teetkalm** [comment]
OK, this re-edit feature seems to be not so simple. It should be implemented by possibility to move existing corners, center, points etc with mouse, but this add-on seem to focus on drawing new shapes.

**Comment by Fuzzyma** [comment]
as i stated in the comment on tsackoverflow: use svg.resize.js. To move shappes you have svg.draggable.js

**Comment by teetkalm** [comment]
thank you, I did not know, that those separate add-ons exist.
