### ISSUE TITLE
Draw done is not fired

### ISSUE THREAD

**Issue by IonicaBizau** [svgdotjs/svg.draw.js#4]
Looks like [this function](https://github.com/Fuzzyma/svg.draw.js/blob/09103ce79dfaf062f8b41fe038ff1f96f8f60abf/src/svg.draw.js#L131-L136) is not used at all. :boom:

**Comment by Fuzzyma** [comment]
read the comment above that function

**Comment by IonicaBizau** [comment]
Oh, got it. :joy:
