### ISSUE TITLE
Refresh plugin

### ISSUE THREAD

**Issue by VictorPulzz** [svgdotjs/svg.draw.js#43]
How I can refresh plugin?
For example, I drew rectangle, and i wont to delete him, because him bad, after I wont to drow new rectangle. I thought I had to stop (poly.draw("cancel")), and then run again poly.draw(), but it did not work. Sombody solve this problem?

**Comment by Fuzzyma** [comment]
Delete it and draw a new one

**Comment by VictorPulzz** [comment]
Hello, this my code, and it does not work:
![image](https://user-images.githubusercontent.com/23406402/45549459-97d41600-b830-11e8-80f0-246f0c769544.png)

**Comment by Fuzzyma** [comment]
`$polygon.remove()` deletes the shape.
