### ISSUE TITLE
Apple IOS events

### ISSUE THREAD

**Issue by bsmaran** [svgdotjs/svg.draw.js#47]
Drawstop and drawpoint events are not triggered in ios.

**Comment by Fuzzyma** [comment]
Unfortunately I dont have any mac device to test my code on. Feel free to create a PR to fix this issue!

**Comment by bsmaran** [comment]
> Unfortunately I dont have any mac device to test my code on. Feel free to create a PR to fix this issue!

I do not have it either. I'm testing on appetize dot io
