### ISSUE TITLE
Draw an arrow

### ISSUE THREAD

**Issue by IonicaBizau** [svgdotjs/svg.draw.js#5]
What's the best way to draw an arrow?

**Comment by Fuzzyma** [comment]
use SVG.invent to create your own shape with its own functions. Than you can add a draw function for it. See [here](https://github.com/wout/svg.js#extending-functionality) for an example.
However - this is not an issue and therefore it should be posted on stackoverflow and not here

**Comment by IonicaBizau** [comment]
Thanks! :+1: 

> However - this is not an issue and therefore it should be posted on stackoverflow and not here

I agree. On SO, this would be off-topic, tho...

**Comment by Fuzzyma** [comment]
take a look at https://github.com/wout/svg.shapes.js - maybe you find some input there
