### ISSUE TITLE
does it support drawing polygon by touching in mobile browser?

### ISSUE THREAD

**Issue by daxavarsanitatvasoft** [svgdotjs/svg.draw.js#50]
I am trying to draw polygon. It works fine with mouse click but when I use mobile to draw polygon by touch. It draws polygon but what to do for finishing drawing polygon. As with enter key you can finish in web browser.

**Comment by Fuzzyma** [comment]
Enter key is just the default behavior. You can call the done function yourself any time you want. E. G. A long touch or something like that
