### ISSUE TITLE
how can i import svg.draw in angular project?

### ISSUE THREAD

**Issue by hessam963** [svgdotjs/svg.draw.js#51]
hey.
I want to use svg draw in angular 8 project
import * as SVG from "@svgdotjs/svg.js";
import 'svg.draw.js';
` @Component({
    selector: 'kt-floor-plan',
   templateUrl: './floor-plan.component.html',
   styleUrls: ['./floor-plan.component.scss']
  })
export class FloorPlanComponent implements OnInit {
	draw: Svg
  constructor() { }

  ngOnInit() {
	  this.draw = SVG().addTo('#canvas').size(300, 300)
	 // this.draw.line(0, 0, 100, 150).stroke({ width: 1 });
	  let line = this.draw.line(0, 100, 100, 0).move(20, 20)
	  line.stroke({ color: '#f06', width: 10, linecap: 'round' });
	  line.draw()

  }`
I get this error  Property 'draw' does not exist on type 'Line'.

**Comment by dacbreakpoint** [comment]
I am interested on this question, too. Is it possible to call the draw() function even without an typescript type declaration?

**Comment by Fuzzyma** [comment]
Thats a pure typescript question. Please try to search for this seperately

**Comment by Fuzzyma** [comment]
Simplest solution: Cast the object to <any> and you are good to go. A more enhanced solution would be to add the draw method via interface
