### ISSUE TITLE
Question: how to remove a selected element drawn with svg.draw.js

### ISSUE THREAD

**Issue by mchendriks** [svgdotjs/svg.draw.js#52]
I'm building a simple svg drawing script. 

http://digirent.nl/examples/svgdraw/draw.html

What I want to achieve is select one or more elements and after clicking on delete remove them.
I'm using the select plugin, the object is removed but the select handles are not. Any ideas how to handle this are appreciated.

**Comment by Fuzzyma** [comment]
Just unselect it before calling remove. Unselecting removes all handlers

**Comment by mchendriks** [comment]
Thanks, thats what i was trying to do.

I'm using the following code, but this results in a error. selectize function or method not available.

$("[clicked=1]").each(function(index,  value) {
  $(this).selectize(false);
   $(this).remove();
}

**Comment by Fuzzyma** [comment]
Obviously you are mixing up jquery with svg.js.
Try `SVG.adopt(this).selectize(false)` instead

**Comment by mchendriks** [comment]
works perfect! thanks.
