### ISSUE TITLE
event.detail.p should be a SVG.Point

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.draw.js#57]
While creating an answer for https://stackoverflow.com/questions/59585107/how-do-i-draw-an-svg-polyline-with-45-degree/59652093#59652093, I found that all events emit a [SVGPoint] as `p` and not a [SVG.Point].

The [SVG.Point] has the `clone()`method which is very useful when you want to store a point from an event for later use. Currently you will get a reference to the [SVGPoint] which changes with `mousemove`.

As an example:

```js
let point
rect.on('drawstart', event => {
  point = event.detail.p
})
```
In the above snippet `point` will always update as the mouse moves because it is a reference.

The work-around is to get the primitive values and store them instead. As shown here:

```js
const point = {x:0,y:0}
rect.on('drawstart', event => {
  const {x,y} = event.detail.p
  point.x = x
  point.y = y
})
```

But it would be much nicer if one could just use the `clone()` method. As in this example:

```js
let point
rect.on('drawstart', event => {
  point = event.detail.p.clone()
})
```

[SVGPoint]: https://developer.mozilla.org/en-US/docs/Web/API/SVGPoint
[SVG.Point]: https://svgjs.com/docs/2.7/classes/#svg-point

**Comment by Fuzzyma** [comment]
Sorry for never replaying @dotnetCarpenter. I was always wondering whats the better solution to this issue. SVG.Point is often not supported where you would expect it (e.g. passing an array of points to the polygon constructor). And I think in this case I would rather not create an extra object for every event since it adds up.
Btw, we should have a virtual coffee someday :D

**Comment by dotnetCarpenter** [comment]
@Fuzzyma virtual coffee sounds good. Where is the hang out room for svg.js these days?

**Comment by dotnetCarpenter** [comment]
Looking at my old code in the WIP_SVG.Point branch - there is a very nice demo of snapping to a 45 degree angle.
The rest looks like stuff I tried out and have no current value.

**Comment by Fuzzyma** [comment]
@dotnetCarpenter now I am curious about that wonderful piece of core :D

I would just suggest Google meet.
I can send you an invite if you give me a day and time :D. I will travel Tomorrow and Tuesday. Besides that, I should have time :)
