### ISSUE TITLE
Edit text

### ISSUE THREAD

**Issue by IonicaBizau** [svgdotjs/svg.draw.js#6]
How to edit a text element in svg?

`contenteditable` on the wrapping div works, but I'm looking for a more native solution. :smile:

**Comment by Fuzzyma** [comment]
...same as in #5 
editing text in svg is not easy to do. contenteditable only works on the wrapping div.
SVG2 will add this attribute to the SVG namespace, too.
If you want do it anway you have to do the whole manipulation yourself

**Comment by IonicaBizau** [comment]
:+1:

**Comment by Fuzzyma** [comment]
there are hacks which adds htmlinputs as overlay to the svgtext to achieve what you want

**Comment by IonicaBizau** [comment]
@Fuzzyma Thanks! :cake: :grin:
