### ISSUE TITLE
No "drawCircles" option in npm package

### ISSUE THREAD

**Issue by shurfee** [svgdotjs/svg.draw.js#64]
Hi! Thank you for helpful plugin.

Could you please update npm package to include latest changes? This merged pr is not included in npm package: https://github.com/svgdotjs/svg.draw.js/pull/62

Thank you in advance.

**Comment by vovaoecoyc** [comment]
Up! When i use method `draw` by `'mousemove'` event, i get some problems with rendering. You can see it in perfomanse tab of chrome dev-tools. This is due to the drawing of the circles.
