### ISSUE TITLE
How to deal with touchstart - touchmove - touchend ?

### ISSUE THREAD

**Issue by Kamoba** [svgdotjs/svg.draw.js#66]
I'm using it for drawing with mouse (`draw.polyline()`) on a TouchDevice (Window tablet) and it's not working, not geting the event `mousedown and mouseup`, so i replace them with `touchstart and touchend ` but gor error:
```
Uncaught TypeError: SVGPoint.x setter: Value being assigned is not a finite floating-point value.
```

Code:
```
    draw.on('mousedown', event => { 
      const shape = getDrawObject();
      shapes[index] = shape;
      shape.draw(event);
    });
```
but work on pc.

**Comment by ayhanap** [comment]
I was checking this too but as I understand current library doesn't support touch events. Because coordinates in touch events are at `e.changedTouches[0].clientX` instead of the current code which only uses `e.clientX`

**Comment by nedredmond** [comment]
@Kamoba You should be able to use [pointerdown](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) and [pointerup](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerup_event)
