### ISSUE TITLE
Create a connection between area and polyline

### ISSUE THREAD

**Issue by SilverGaucho** [svgdotjs/svg.draw.js#67]
Hei there!

I'm trying to create a connection between an area and a polyline in a classical drag and drop "square and lines" environment.

- During "drawpoint" of the polyline I check if i'm over another object. If the check is true, I want to add the point to target element - internal set
- When I drag the target element I want to move the point added to the set accordingly with the target

Now, the drawpoint let me add to the set, not the point but the entire polyline therefore on the drag event I do not have the interested point and it is difficult to retreive the desired point.

Any smart solution ?
Thanks for the help

**Comment by Fuzzyma** [comment]
hey @SilverGaucho sorry for not responding. I guess I looked at the issue and had no solution at hand and forgot about it.
If its still relevant I would advise you to ask this question on stackoverflow since it seems to involve more technical aspects than only svg.js.
